/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Git's well-known empty-tree hash (`4b825dc6…`). */
export declare function emptyTreeHash(): string
/**
 * A commit identity (author or committer). `timeSeconds`/`offsetMinutes` are
 * optional; when omitted the current wall-clock time at UTC is used. Pass them
 * explicitly to reproduce a specific commit (e.g. match `git commit-tree`
 * under pinned `GIT_AUTHOR_DATE`/`GIT_COMMITTER_DATE`).
 */
export interface Signature {
  name: string
  email: string
  timeSeconds?: number
  offsetMinutes?: number
}
/**
 * A handle to a git repository, backed by gix.
 *
 * Stored as a `ThreadSafeRepository` so the handle is `Send + Sync` and can be
 * cheaply cloned into each `Tree`; every call derives a thread-local
 * `gix::Repository` via `to_thread_local()`.
 */
export declare class Repo {
  /**
   * Open a repository at `gitDir` (a `.git` directory, or any path gix can
   * discover a repo from).
   */
  static open(gitDir: string): Repo
  /**
   * Resolve a ref (branch, tag, or commit hash) to its tree and return a
   * mutable, in-memory view of it.
   */
  createTreeFromRef(gitRef: string): Tree
  /** Create a fresh empty, mutable in-memory tree rooted at this repo. */
  createTree(): Tree
  /**
   * Write a commit object pointing at `treeHash` with `parents`. `author`
   * and `committer` are optional; each falls back to the repo's configured
   * identity, then a "holo-tree" default. Returns the new commit hash.
   */
  commitTree(treeHash: string, parents: Array<string>, message: string, author?: Signature | undefined | null, committer?: Signature | undefined | null): string
  /** Point a ref at an object hash. */
  updateRef(refname: string, hash: string): void
}
/**
 * A mutable, in-memory git tree.
 *
 * Holds its own clone of the repo handle so JS callers don't thread a repo
 * argument through every call.
 *
 * Phase-C finding #1: holo-tree's `MutableTree` takes `&gix::Repository` on
 * nearly every method and keeps a *thread-local* tree cache. We smooth the
 * first half here (the handle lives on the `Tree`) but NOT the second: each
 * call does `to_thread_local()`, and whether holo-tree's thread-local cache
 * stays warm across libuv-dispatched calls is the open ergonomics question to
 * resolve upstream (e.g. a repo-bound tree handle, or an explicit session/
 * cache object the consumer owns).
 */
export declare class Tree {
  /**
   * Hash `content` (UTF-8 text) as a blob and insert it at `path`, creating
   * intermediate trees as needed. Returns the blob hash.
   */
  writeChild(path: string, content: string): string
  /** Hash raw bytes as a blob and insert at `path`. Binary-safe. */
  writeChildBytes(path: string, content: Buffer): string
  /** Read a blob's bytes at `path`, or `null` if no blob exists there. */
  readBlob(path: string): Buffer | null
  /** Delete a child at a deep `path`. Returns whether it existed. */
  deleteChildDeep(path: string): boolean
  /** Flush dirty subtrees to the ODB and return the resulting tree hash. */
  write(): string
}
