#!/bin/bash

INPUT_TREE="${1?<input> required}"

# redirect all output to stderr
{
  if [ -z "${HOLOLENS_SENCHA_PKG}" ]; then
    echo "hololens.sencha.pkg required configuation value is missing from the lens environment"
    exit 1;
  fi

  if [ "$(git cat-file -t ${INPUT_TREE}:packages/${HOLOLENS_SENCHA_PKG} 2> /dev/null)" != "tree" ]; then
    echo "hololens.sencha.pkg '${HOLOLENS_SENCHA_PKG}' does not match a top-level subtree of the input tree"
    exit 1;
  fi

  # export git tree to disk
  git holo lens export-tree "${INPUT_TREE}"

  # execute compilation
  pushd "${GIT_WORK_TREE}/packages/${HOLOLENS_SENCHA_PKG}" > /dev/null
  build-package
  build_status=$?
  popd > /dev/null

  # process result
  if [ $build_status -ne 0 ]; then
    echo -e "\n${HOLOLENS_SENCHA_PKG} build failed with exit status ${build_status}"
    exit
  fi

  echo -e "\n${HOLOLENS_SENCHA_PKG} build completed successfully"

  # add output to git index
  git reset HEAD && git add -f "packages/${HOLOLENS_SENCHA_PKG}/build"

} 1>&2

# output tree hash
git write-tree --prefix="packages/${HOLOLENS_SENCHA_PKG}/build"
