/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Internal self-test hook: deliberately panics inside the binding so the
 * test suite can prove that a panic surfaces as a catchable JS error with
 * code `PANIC` rather than aborting the host process. Never call this
 * outside tests.
 */
export declare function __triggerPanicForTest(): void
/**
 * Compose a holobranch to its **pre-lens tree**: the extends chain and all
 * mappings composed per `specs/behaviors/composition.md`, with
 * `.holo/{branches,sources}` stripped but the final `.holo` strip skipped so
 * the host's lens phase can discover `.holo/lenses` and `.holo/config.toml`.
 * Returns the composed tree hash.
 */
export declare function compositeBranch(gitDir: string, rootTree: string, holobranch: string): string
/**
 * Full composition-only projection of a holobranch, including the final
 * metadata strip — hash-equal to the legacy engine with lensing disabled.
 * Returns the projected tree hash.
 */
export declare function projectBranch(gitDir: string, rootTree: string, holobranch: string): string
/** A source definition for `projectPlan`. Mirrors `ProjectionPlan.addSource`. */
export interface JsPlanSource {
  name: string
  url?: string
  ref?: string
  projectHolobranch?: string
}
/**
 * A mapping definition for `projectPlan`. Mirrors `ProjectionPlan.addMapping`
 * defaults: `files` `["**"]`, `root`/`output` `"."`, `layer` = source name.
 */
export interface JsPlanMapping {
  source: string
  files?: Array<string>
  root?: string
  output?: string
  layer?: string
  after?: Array<string>
  before?: Array<string>
}
/**
 * Compose git trees from structured source/mapping definitions — the
 * `ProjectionPlan` path, no `.holo/` config needed. Returns the composed
 * tree hash (full projection, metadata stripped).
 */
export declare function projectPlan(gitDir: string, sources: Array<JsPlanSource>, mappings: Array<JsPlanMapping>): string
/** Engine performance counters — process-global, monotonic, metrics only. */
export interface Stats {
  treesRead: number
  treesWritten: number
  treesSkippedClean: number
  cacheHits: number
  cacheMisses: number
  blobsRead: number
}
/** Current engine performance counters. */
export declare function stats(): Stats
/** Reset engine counters and module-level caches. */
export declare function resetStats(): void
