#!/bin/bash

INPUT_TREE="${1?<input> required}"

# redirect all output to stderr
{
  if [ -z "${HOLOLENS_SENCHA_APP}" ]; then
    echo "hololens.sencha.app required configuation value is missing from the lens environment"
    exit 1;
  fi

  if [ "$(git cat-file -t ${INPUT_TREE}:${HOLOLENS_SENCHA_APP} 2> /dev/null)" != "tree" ]; then
    echo "hololens.sencha.app '${HOLOLENS_APP}' does not match a top-level subtree of the input tree"
    exit 1;
  fi

  # export git tree to disk
  git holo lens export-tree "${INPUT_TREE}"

  # execute compilation
  pushd "${GIT_WORK_TREE}/${HOLOLENS_SENCHA_APP}" > /dev/null
  build-app
  build_status=$?
  popd > /dev/null

  # process result
  if [ $build_status -ne 0 ]; then
    echo -e "\n${HOLOLENS_SENCHA_APP} build failed with exit status ${build_status}"
    exit
  fi

  echo -e "\n${HOLOLENS_SENCHA_APP} build completed successfully"

  # add output to git index
  git add "${HOLOLENS_SENCHA_APP}/build"

} 1>&2

# output tree hash
git write-tree --prefix="${HOLOLENS_SENCHA_APP}/build"
